// QuestionSet.js
export const quiz = {
    questions: [
        {
            id: 1,
            question: 'Which gender do you identify with?',
            answers: ['Female',
                'Male',
                'Non-binary',
                'Prefer not to answer'],
            correctAnswer: 'Application Programming Interface',
        },

        {
            id: 2,
            question: `Have you ever been diagnosed with Binge Eating Disorder (BED)?`,
            answers: ['I am diagnosed by a doctor.', 'I am self diagnosed.', 'I suspect I might have BED.', 'Not with BED, but another eating disorder.','Soomething else'],
            correctAnswer: 'JavaScript',
        },
        {
            id: 3,
            question: 'Do you feel in control of how much you eat?',
            answers: ['All the time', 'A lot of the time',
                'Sometimes', 'Rarely'],
            correctAnswer: 'Querying databases',
        },
        {
            id: 4,
            question: 'Do you eat meals much more quickly than others and seem to eat a lot more than others as well?',
            answers: ['All the time', 'A lot of the time',
                'Sometimes', 'Rarely', 'Never'],
            correctAnswer: 'Model View Controller',
        },
        {
            id: 5,
            question: 'Do you have a strong habit of eating when you are bored such that nothing else can distract you?',
            answers: ['All the time', 'A lot of the time',
                'Sometimes', 'Rarely', 'Never'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 6,
            question: 'Do you often feel desperate that you cannot be more in control of what you eat?',
            answers: ['All the time', 'A lot of the time',
                'Sometimes', 'Rarely', 'Never'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 7,
            question: 'Do you often eat, even though you are not hungry, because of habit?',
            answers: ['All the time', 'A lot of the time',
                'Sometimes', 'Rarely', 'Never'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 8,
            question: 'Is it esy for you to get back on track with a diet or healthy regime?',
            answers: ['Application Programming Interface',
                'Advanced Programming Interface',
                'Application Program Interface',
                'Automated Programming Interface'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 9,
            question: 'What does API stand for?',
            answers: ['Application Programming Interface',
                'Advanced Programming Interface',
                'Application Program Interface',
                'Automated Programming Interface'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 8,
            question: 'What does API stand for?',
            answers: ['Application Programming Interface',
                'Advanced Programming Interface',
                'Application Program Interface',
                'Automated Programming Interface'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 8,
            question: 'What does API stand for?',
            answers: ['Application Programming Interface',
                'Advanced Programming Interface',
                'Application Program Interface',
                'Automated Programming Interface'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 8,
            question: 'What does API stand for?',
            answers: ['Application Programming Interface',
                'Advanced Programming Interface',
                'Application Program Interface',
                'Automated Programming Interface'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 8,
            question: 'What does API stand for?',
            answers: ['Application Programming Interface',
                'Advanced Programming Interface',
                'Application Program Interface',
                'Automated Programming Interface'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 8,
            question: 'What does API stand for?',
            answers: ['Application Programming Interface',
                'Advanced Programming Interface',
                'Application Program Interface',
                'Automated Programming Interface'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 8,
            question: 'What does API stand for?',
            answers: ['Application Programming Interface',
                'Advanced Programming Interface',
                'Application Program Interface',
                'Automated Programming Interface'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 8,
            question: 'What does API stand for?',
            answers: ['Application Programming Interface',
                'Advanced Programming Interface',
                'Application Program Interface',
                'Automated Programming Interface'],
            correctAnswer: 'Application Programming Interface',
        },
        {
            id: 8,
            question: 'What does API stand for?',
            answers: ['Application Programming Interface',
                'Advanced Programming Interface',
                'Application Program Interface',
                'Automated Programming Interface'],
            correctAnswer: 'Application Programming Interface',
        },
    ],
};